sudo: false

language: cpp

compiler:
    - gcc

env:
    -
    - OMP_NUM_THREADS=1
    - OMP_NUM_THREADS=4

script:
    - cppcheck --error-exitcode=2 .
    - make VERBOSE=1 test
    - ./memcheck.bash
    - bash -c './build/perceptualdiff | grep -i openmp'

after_success:
    - pip install --user cpp-coveralls
    - if [ "$CC" == "gcc" ];
      then PATH="$PATH:$HOME/.local/bin" ./coveralls.bash; fi

addons:
    apt:
        packages:
            - cmake
            - cppcheck
            - libfreeimage-dev
            - valgrind
